/*******************************************************************
 * Decompiled By: Bog
 * Decompiled File: maps\mp\mp_prague_fx.gsc
 * Game: Call of Duty: WWII
 * Platform: PC
 * Function Count: 1
 * Decompile Time: 33 ms
 * Timestamp: 10/27/2023 3:15:53 AM
*******************************************************************/

//Function Number: 1
func_00F9()
{
	level.var_611["mp_prague_glow_interior_dim"] = loadfx("vfx/map/mp_prauge/mp_prague_glow_interior_dim");
	level.var_611["mp_prague_glow_street_lamp_1_rnr"] = loadfx("vfx/map/mp_prauge/mp_prague_glow_street_lamp_1_rnr");
	level.var_611["mp_prague_oil_lamp"] = loadfx("vfx/map/mp_prauge/mp_prague_oil_lamp");
	level.var_611["mp_prague_snow_alleyways"] = loadfx("vfx/map/mp_prauge/mp_prague_snow_alleyways");
	level.var_611["mp_prague_foam_center_out_lrg"] = loadfx("vfx/map/mp_prauge/mp_prague_foam_center_out_lrg");
	level.var_611["mp_prague_water_foam_ocean_med"] = loadfx("vfx/map/mp_prauge/mp_prague_water_foam_ocean_med");
	level.var_611["mp_prague_water_foam_ocean_lrg_single"] = loadfx("vfx/map/mp_prauge/mp_prague_water_foam_ocean_lrg_single");
	level.var_611["mp_prague_water_foam_ocean_lrg"] = loadfx("vfx/map/mp_prauge/mp_prague_water_foam_ocean_lrg");
	level.var_611["mp_prague_water_foam_ocean"] = loadfx("vfx/map/mp_prauge/mp_prague_water_foam_ocean");
	level.var_611["mp_prague_stair_fire_smoke"] = loadfx("vfx/map/mp_prauge/mp_prague_stair_fire_smoke");
	level.var_611["mp_prague_water_foam_splash_01"] = loadfx("vfx/map/mp_prauge/mp_prague_water_foam_splash_01");
	level.var_611["mp_prague_spark_burst_runner"] = loadfx("vfx/map/mp_prauge/mp_prague_spark_burst_runner");
	level.var_611["mp_prague_spark_burst_1"] = loadfx("vfx/map/mp_prauge/mp_prague_spark_burst_1");
	level.var_611["mp_prague_fire_vehicle_1"] = loadfx("vfx/map/mp_prauge/mp_prague_fire_vehicle_1");
	level.var_611["mp_prague_window_smk_lrg"] = loadfx("vfx/map/mp_prauge/mp_prague_window_smk_lrg");
	level.var_611["mp_prague_light_cone_canal"] = loadfx("vfx/map/mp_prauge/mp_prague_light_cone_canal");
	level.var_611["mp_prague_smk_embers_fire_small"] = loadfx("vfx/map/mp_prauge/mp_prague_smk_embers_fire_small");
	level.var_611["mp_prague_fire_lp_flat_area"] = loadfx("vfx/map/mp_prauge/mp_prague_fire_lp_flat_area");
	level.var_611["mp_prague_steam_sm_vent_slow_wind"] = loadfx("vfx/map/mp_prauge/mp_prague_steam_sm_vent_slow_wind");
	level.var_611["mp_prague_falling_water_drip_central_fast"] = loadfx("vfx/map/mp_prauge/mp_prague_falling_water_drip_central_fast");
	level.var_611["mp_prague_dripping_water_40x40"] = loadfx("vfx/map/mp_prauge/mp_prague_dripping_water_40x40");
	level.var_611["mp_prague_water_flow_rain_gutter_small"] = loadfx("vfx/map/mp_prauge/mp_prague_water_flow_rain_gutter_small");
	level.var_611["mp_prague_water_gutter_splash_sm_loop"] = loadfx("vfx/map/mp_prauge/mp_prague_water_gutter_splash_sm_loop");
	level.var_611["mp_prague_cold_steam_cannal_vistas"] = loadfx("vfx/map/mp_prauge/mp_prague_cold_steam_cannal_vistas");
	level.var_611["vf_wind_mp_prague_a"] = loadfx("vfx/vectorfield/vf_wind_mp_prague_a");
	level.var_611["mp_prague_mist_01"] = loadfx("vfx/map/mp_prauge/mp_prague_mist_01");
	level.var_611["mp_prague_smoke_chimney_thin_sm_c"] = loadfx("vfx/map/mp_prauge/mp_prague_smoke_chimney_thin_sm_c");
	level.var_611["mp_prague_motes_interior_01"] = loadfx("vfx/map/mp_prauge/mp_prague_motes_interior_01");
	level.var_611["mp_prague_paper_blown_dark_a"] = loadfx("vfx/map/mp_prauge/mp_prague_paper_blown_dark_a");
	level.var_611["mp_prague_snow_attach_player_hvy"] = loadfx("vfx/map/mp_prauge/mp_prague_snow_attach_player_hvy");
	level.var_611["mp_prague_cold_steam_centercourt"] = loadfx("vfx/map/mp_prauge/mp_prague_cold_steam_centercourt");
	level.var_611["mp_prague_ambient_snowing"] = loadfx("vfx/map/mp_prauge/mp_prague_ambient_snowing");
	level.var_611["mp_prague_cold_steam_white_cannal"] = loadfx("vfx/map/mp_prauge/mp_prague_cold_steam_white_cannal");
	level.var_611["mp_prague_ground_snow_light_wind_runner"] = loadfx("vfx/map/mp_prauge/mp_prague_ground_snow_light_wind_runner");
	level.var_611["mp_prague_snow_light_wind_gust_lrg_runner"] = loadfx("vfx/map/mp_prauge/mp_prague_snow_light_wind_gust_lrg_runner");
	level.var_611["mp_prague_snow_light_wind_gust_runner"] = loadfx("vfx/map/mp_prauge/mp_prague_snow_light_wind_gust_runner");
	level.var_611["mp_prague_dust_blowing_ground_1"] = loadfx("vfx/map/mp_prauge/mp_prague_dust_blowing_ground_1");
	level.var_611["mp_prague_leaves_fall_1"] = loadfx("vfx/map/mp_prauge/mp_prague_leaves_fall_1");
	level.var_611["mp_prague_leaves_ground_blowing_1"] = loadfx("vfx/map/mp_prauge/mp_prague_leaves_ground_blowing_1");
	level.var_611["mp_prague_cold_steam_white_a"] = loadfx("vfx/map/mp_prauge/mp_prague_cold_steam_white_a");
	level.var_611["mp_prague_smoke_chimney_thin_sm_b"] = loadfx("vfx/map/mp_prauge/mp_prague_smoke_chimney_thin_sm_b");
	level.var_611["mp_prague_cold_steam_riverbank_white"] = loadfx("vfx/map/mp_prauge/mp_prague_cold_steam_riverbank_white");
	level.var_611["mp_prague_cold_steam_white"] = loadfx("vfx/map/mp_prauge/mp_prague_cold_steam_white");
	level.var_611["mp_prague_river_steam_stack"] = loadfx("vfx/map/mp_prauge/mp_prague_river_steam_stack");
	level.var_611["mp_prague_falling_water_drip_caves"] = loadfx("vfx/map/mp_prauge/mp_prague_falling_water_drip_caves");
	level.var_611["insect_lrg_flies_flying"] = loadfx("vfx/animal/insect_lrg_flies_flying");
	level.var_611["wind_blowing_leaves_and_needles"] = loadfx("vfx/wind/wind_blowing_leaves_and_needles");
	level.var_611["mp_prague_waterfallsplash_bottom_mill_sml"] = loadfx("vfx/map/mp_prauge/mp_prague_waterfallsplash_bottom_mill_sml");
	level.var_611["mp_prague_waterfall_splash_bottom_mill"] = loadfx("vfx/map/mp_prauge/mp_prague_waterfall_splash_bottom_mill");
	level.var_611["mp_prague_waterfall_splash_base_mill"] = loadfx("vfx/map/mp_prauge/mp_prague_waterfall_splash_base_mill");
	level.var_611["mp_prague_fog_thick_rising_patch_ground"] = loadfx("vfx/map/mp_prauge/mp_prague_fog_thick_rising_patch_ground");
	level.var_611["insects_moths"] = loadfx("vfx/animal/insects_moths");
	level.var_611["ambient_falling_leaves_runner"] = loadfx("vfx/wind/dlc/ambient_falling_leaves_runner");
	level.var_611["vf_wind_mp_prague"] = loadfx("vfx/vf_wind_mp_prague");
	level.var_611["vf_wind_mp_r_dday"] = loadfx("vfx/vectorfield/vf_wind_mp_r_dday");
	level.var_611["mp_prague_vista_bombers"] = loadfx("vfx/map/mp_prauge/mp_prague_vista_bombers");
	level.var_611["mp_prauge_slow_rolling_smk"] = loadfx("vfx/map/mp_prauge/mp_prauge_slow_rolling_smk");
	level.var_611["mp_prauge_low_rolling_smk"] = loadfx("vfx/map/mp_prauge/mp_prauge_low_rolling_smk");
	level.var_611["mp_prague_smk_sml"] = loadfx("vfx/map/mp_prauge/mp_prague_smk_sml");
	level.var_611["mp_prauge_smk_lrg"] = loadfx("vfx/map/mp_prauge/mp_prauge_smk_lrg");
	level.var_611["test_effect"] = loadfx("vfx/test/test_fx");
	level.var_611["mp_prague_chimney_white"] = loadfx("vfx/map/mp_prauge/mp_prague_chimney_white");
	level.var_611["mp_prague_fire_falling_runner"] = loadfx("vfx/map/mp_prauge/mp_prague_fire_falling_runner");
	level.var_611["mp_prague_fire_lp_ceiling_area"] = loadfx("vfx/map/mp_prauge/mp_prague_fire_lp_ceiling_area");
	level.var_611["mp_prague_destroyed_car_fire_a"] = loadfx("vfx/map/mp_prauge/mp_prague_destroyed_car_fire_a");
	level.var_611["mp_prague_fire_smk_m"] = loadfx("vfx/map/mp_prauge/mp_prague_fire_smk_m");
	level.var_611["mp_prague_beach_fish_flop_rnr"] = loadfx("vfx/map/mp_prauge/mp_prague_beach_fish_flop_rnr");
	level.var_611["mp_prague_smoke_chimney_thin_sm"] = loadfx("vfx/map/mp_prauge/mp_prague_smoke_chimney_thin_sm");
	level.var_611["mp_prague_a_steam_stack"] = loadfx("vfx/map/mp_prauge/mp_prague_a_steam_stack");
	level.var_611["mp_prague_smoke_chimney_sm_dark"] = loadfx("vfx/map/mp_prauge/mp_prague_smoke_chimney_sm_dark");
	level.var_611["mp_prague_steam_stack_dark"] = loadfx("vfx/map/mp_prauge/mp_prague_steam_stack_dark");
	level.var_611["mp_prague_steam_stack_white"] = loadfx("vfx/map/mp_prauge/mp_prague_steam_stack_white");
	level.var_611["vf_mp_wind_prague"] = loadfx("vfx/vectorfield/vf_mp_wind_prague");
	level.var_611["mp_prauge_low_rolling_grey_smk"] = loadfx("vfx/map/mp_prauge/mp_prauge_low_rolling_grey_smk");
	level.var_611["mp_prague_fire_smk_sml"] = loadfx("vfx/map/mp_prauge/mp_prague_fire_smk_sml");
	level.var_611["mp_prague_vista_smk"] = loadfx("vfx/map/mp_prauge/mp_prague_vista_smk");
	level.var_611["mp_prague_river_steam_stack"] = loadfx("vfx/map/mp_prauge/mp_prague_river_steam_stack");
	level.var_611["mp_prague_smk_smoldering_crater_a"] = loadfx("vfx/map/mp_prauge/mp_prague_smk_smoldering_crater_a");
	level.var_611["mp_prague_glow_street_lamp_1"] = loadfx("vfx/map/mp_prauge/mp_prague_glow_street_lamp_1");
	level.var_611["mp_prague_destroyed_car_fire_c"] = loadfx("vfx/map/mp_prauge/mp_prague_destroyed_car_fire_c");
	level.var_611["mp_prague_foam_water_wheel"] = loadfx("vfx/map/mp_prauge/mp_prague_foam_water_wheel");
	level.var_611["mp_prague_statue_spotlight"] = loadfx("vfx/map/mp_prauge/mp_prague_statue_spotlight");
	level.var_611["mp_prague_light_flare_interior"] = loadfx("vfx/map/mp_prauge/mp_prague_light_flare_interior");
	level.var_611["mp_prague_light_cone_1_dim"] = loadfx("vfx/map/mp_prauge/mp_prague_light_cone_1_dim");
	level.var_611["mp_prague_vista_smk_vista_03"] = loadfx("vfx/map/mp_prauge/mp_prague_vista_smk_vista_03");
	level.var_611["mp_prague_window_fire_top"] = loadfx("vfx/map/mp_prauge/mp_prague_window_fire_top");
	level.var_611["mp_prague_candle_1"] = loadfx("vfx/map/mp_prauge/mp_prague_candle_1");
	level.var_611["mp_prague_light_cone_simple"] = loadfx("vfx/map/mp_prauge/mp_prague_light_cone_simple");
	level.var_611["mp_prague_cold_steam_whisps_strip"] = loadfx("vfx/map/mp_prauge/mp_prague_cold_steam_whisps_strip");
	level.var_611["mp_prague_foam_constant"] = loadfx("vfx/map/mp_prauge/mp_prague_foam_constant");
	level.var_611["mp_prague_cold_steam_whisps"] = loadfx("vfx/map/mp_prauge/mp_prague_cold_steam_whisps");
	level.var_611["mp_prague_ash_embers"] = loadfx("vfx/map/mp_prauge/mp_prague_ash_embers");
	level.var_611["mp_prague_oil_smk"] = loadfx("vfx/map/mp_prauge/mp_prague_oil_smk");
	level.var_611["mp_prague_tree_fire"] = loadfx("vfx/map/mp_prauge/mp_prague_tree_fire");
	level.var_611["mp_prague_crater_fire_lrg_b"] = loadfx("vfx/map/mp_prauge/mp_prague_crater_fire_lrg_b");
	level.var_611["mp_prague_crater_fire_lrg_a"] = loadfx("vfx/map/mp_prauge/mp_prague_crater_fire_lrg_a");
	level.var_611["mp_prague_crater_fire_sml"] = loadfx("vfx/map/mp_prauge/mp_prague_crater_fire_sml");
	level.var_611["mp_prague_crater_fire_lrg"] = loadfx("vfx/map/mp_prauge/mp_prague_crater_fire_lrg");
	level.var_611["mp_prague_bullet_wall_steam"] = loadfx("vfx/map/mp_prauge/mp_prague_bullet_wall_steam");
	level.var_611["mp_prague_tire_skidmark_steam"] = loadfx("vfx/map/mp_prauge/mp_prague_tire_skidmark_steam");
	level.var_611["mp_prague_vista_smk_vista_thin"] = loadfx("vfx/map/mp_prauge/mp_prague_vista_smk_vista_thin");
	level.var_611["mp_prague_smoke_chimney_vista_1"] = loadfx("vfx/map/mp_prauge/mp_prague_smoke_chimney_vista_1");
	level.var_611["mp_prague_foam_center_out_lrg_runner"] = loadfx("vfx/map/mp_prauge/mp_prague_foam_center_out_lrg_runner");
	level.var_611["mp_prague_snow_ground_light_window"] = loadfx("vfx/map/mp_prauge/mp_prague_snow_ground_light_window");
	level.var_611["mp_prague_cold_steam_white_cannal_nolit"] = loadfx("vfx/map/mp_prauge/mp_prague_cold_steam_white_cannal_nolit");
	level.var_611["mp_prague_dripping_water_100x100"] = loadfx("vfx/map/mp_prauge/mp_prague_dripping_water_100x100");
	level.var_611["mp_prague_fire_licks_xsmall_no_light_c"] = loadfx("vfx/map/mp_prauge/mp_prague_fire_licks_xsmall_no_light_c");
	level.var_611["mp_prague_smk_smoldering_crater"] = loadfx("vfx/map/mp_prauge/mp_prague_smk_smoldering_crater");
	level.var_611["mp_prague_steam_01"] = loadfx("vfx/map/mp_prauge/mp_prague_steam_01");
	level.var_611["mp_prague_vista_smk_vista_02"] = loadfx("vfx/map/mp_prauge/mp_prague_vista_smk_vista_02");
	level.var_611["mp_prague_smk_vista_large_01"] = loadfx("vfx/map/mp_prauge/mp_prague_smk_vista_large_01");
	level.var_611["mp_prague_snow_ground_light_wind_lp_strip"] = loadfx("vfx/map/mp_prauge/mp_prague_snow_ground_light_wind_lp_strip");
	level.var_611["mp_prague_motes_interior_02"] = loadfx("vfx/map/mp_prauge/mp_prague_motes_interior_02");
	level.var_611["mp_prague_dripping_water_ledge"] = loadfx("vfx/map/mp_prauge/mp_prague_dripping_water_ledge");
	level.var_611["mp_prague_snow_attach_player_small_b"] = loadfx("vfx/map/mp_prauge/mp_prague_snow_attach_player_small_b");
	level.var_611["mp_prague_snow_attach_player_small"] = loadfx("vfx/map/mp_prauge/mp_prague_snow_attach_player_small");
	level.var_611["mp_prague_dripping_water_10x10"] = loadfx("vfx/map/mp_prauge/mp_prague_dripping_water_10x10");
	level.var_611["mp_prague_steam_sm_vent_slow_yellow"] = loadfx("vfx/map/mp_prauge/mp_prague_steam_sm_vent_slow_yellow");
	level.var_611["mp_prague_water_gutter_small"] = loadfx("vfx/map/mp_prauge/mp_prague_water_gutter_small");
	level.var_611["mp_prague_burning_window_smoke"] = loadfx("vfx/map/mp_prauge/mp_prague_burning_window_smoke");
	level.var_611["mp_prague_snow_ground_light_wind_lp"] = loadfx("vfx/map/mp_prauge/mp_prague_snow_ground_light_wind_lp");
	level.var_611["mp_prague_maple_falling_leaves_runner"] = loadfx("vfx/map/mp_prauge/mp_prague_maple_falling_leaves_runner");
	level.var_611["mp_prague_falling_ledge_snow_runner"] = loadfx("vfx/map/mp_prauge/mp_prague_falling_ledge_snow_runner");
	level.var_611["mp_prague_ground_leaves_blowing_slow_a"] = loadfx("vfx/map/mp_prauge/mp_prague_ground_leaves_blowing_slow_a");
	level.var_611["mp_prague_destroyed_car_fire_b"] = loadfx("vfx/map/mp_prauge/mp_prague_destroyed_car_fire_b");
	level.water_wake = "vfx/treadfx/body_wake_water_canal";
	level.water_wake_stationary = "vfx/treadfx/body_wake_water_stationary_canal";
}