/*******************************************************************
 * Decompiled By: Bog
 * Decompiled File: maps\mp\mp_paris_s2_fx.gsc
 * Game: Call of Duty: WWII
 * Platform: PC
 * Function Count: 1
 * Decompile Time: 32 ms
 * Timestamp: 10/27/2023 3:15:51 AM
*******************************************************************/

//Function Number: 1
func_00F9()
{
	level.var_611["paris_light_cone_large"] = loadfx("vfx/map/mp_paris_s2/paris_light_cone_large");
	level.var_611["paris_tank_treads_dust"] = loadfx("vfx/map/mp_paris_s2/paris_tank_treads_dust");
	level.var_611["paris_tank_exhaust"] = loadfx("vfx/map/mp_paris_s2/paris_tank_exhaust");
	level.var_611["paris_smoke_medium_2_window"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_medium_2_window");
	level.var_611["paris_embers_ash_white_1"] = loadfx("vfx/map/mp_paris_s2/paris_embers_ash_white_1");
	level.var_611["paris_light_glow_simple_white"] = loadfx("vfx/map/mp_paris_s2/paris_light_glow_simple_white");
	level.var_611["paris_smoke_ceiling_1_column"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_ceiling_1_column");
	level.var_611["paris_steam_stack_dark_wind"] = loadfx("vfx/map/mp_paris_s2/paris_steam_stack_dark_wind");
	level.var_611["paris_steam_stack_dark"] = loadfx("vfx/map/mp_paris_s2/paris_steam_stack_dark");
	level.var_611["paris_smoke_chimney_medium"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_chimney_medium");
	level.var_611["paris_smoke_chimney_sm_dark"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_chimney_sm_dark");
	level.var_611["paris_smoke_tank_1"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_tank_1");
	level.var_611["paris_birds_opening_burst"] = loadfx("vfx/map/mp_paris_s2/paris_birds_opening_burst");
	level.var_611["paris_flashlight_2"] = loadfx("vfx/map/mp_paris_s2/paris_flashlight_2");
	level.var_611["paris_smoke_chimney_thin_embers_sm"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_chimney_thin_embers_sm");
	level.var_611["paris_smoke_ceiling_1"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_ceiling_1");
	level.var_611["paris_paper_blowing_rnr"] = loadfx("vfx/map/mp_paris_s2/paris_paper_blowing_rnr");
	level.var_611["paris_birds_x_rnr"] = loadfx("vfx/map/mp_paris_s2/paris_birds_x_rnr");
	level.var_611["paris_birds_x"] = loadfx("vfx/map/mp_paris_s2/paris_birds_x");
	level.var_611["paris_embers_1"] = loadfx("vfx/map/mp_paris_s2/paris_embers_1");
	level.var_611["paris_flashlight"] = loadfx("vfx/map/mp_paris_s2/paris_flashlight");
	level.var_611["paris_smoke_tank_barrel"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_tank_barrel");
	level.var_611["paris_light_glow_1"] = loadfx("vfx/map/mp_paris_s2/paris_light_glow_1");
	level.var_611["paris_light_shafts_sml"] = loadfx("vfx/map/mp_paris_s2/paris_light_shafts_sml");
	level.var_611["paris_insects_flies_landing"] = loadfx("vfx/map/mp_paris_s2/paris_insects_flies_landing");
	level.var_611["paris_light_cone_1_moths"] = loadfx("vfx/map/mp_paris_s2/paris_light_cone_1_moths");
	level.var_611["paris_light_cone_1"] = loadfx("vfx/map/mp_paris_s2/paris_light_cone_1");
	level.var_611["paris_light_shafts_fire_room"] = loadfx("vfx/map/mp_paris_s2/paris_light_shafts_fire_room");
	level.var_611["paris_fire_lp_ceiling_beam_med"] = loadfx("vfx/map/mp_paris_s2/paris_fire_lp_ceiling_beam_med");
	level.var_611["paris_smk_embers_fire_small"] = loadfx("vfx/map/mp_paris_s2/paris_smk_embers_fire_small");
	level.var_611["paris_house_interior_ash_embers_falling"] = loadfx("vfx/map/mp_paris_s2/paris_house_interior_ash_embers_falling");
	level.var_611["paris_dust_falling_lp_sm"] = loadfx("vfx/map/mp_paris_s2/paris_dust_falling_lp_sm");
	level.var_611["paris_ground_smoke_low_fill"] = loadfx("vfx/map/mp_paris_s2/paris_ground_smoke_low_fill");
	level.var_611["paris_fire_ground_small_1"] = loadfx("vfx/map/mp_paris_s2/paris_fire_ground_small_1");
	level.var_611["paris_fire_lp_ceiling_beam_small"] = loadfx("vfx/map/mp_paris_s2/paris_fire_lp_ceiling_beam_small");
	level.var_611["aparis_fire_lp_ceiling_beam_med"] = loadfx("vfx/map/mp_paris_s2/aparis_fire_lp_ceiling_beam_med");
	level.var_611["paris_fire_crawl_wall_lrg_cheap"] = loadfx("vfx/map/mp_paris_s2/paris_fire_crawl_wall_lrg_cheap");
	level.var_611["paris_ark_steam_stack"] = loadfx("vfx/map/mp_paris_s2/paris_ark_steam_stack");
	level.var_611["paris_leaves_falling_maple_rnr"] = loadfx("vfx/map/mp_paris_s2/paris_leaves_falling_maple_rnr");
	level.var_611["paris_debris_blowing_lp"] = loadfx("vfx/map/mp_paris_s2/paris_debris_blowing_lp");
	level.var_611["paris_ground_smoke_low"] = loadfx("vfx/map/mp_paris_s2/paris_ground_smoke_low");
	level.var_611["paris_motes_interior_1"] = loadfx("vfx/map/mp_paris_s2/paris_motes_interior_1");
	level.var_611["paris_fire_lp_m_base_window_vf"] = loadfx("vfx/map/mp_paris_s2/paris_fire_lp_m_base_window_vf");
	level.var_611["paris_fire_lp_s_windy_vf_blacksmk"] = loadfx("vfx/map/mp_paris_s2/paris_fire_lp_s_windy_vf_blacksmk");
	level.var_611["paris_dust_debris_blowing_sm_lp"] = loadfx("vfx/map/mp_paris_s2/paris_dust_debris_blowing_sm_lp");
	level.var_611["paris_steam_stack_black"] = loadfx("vfx/map/mp_paris_s2/paris_steam_stack_black");
	level.var_611["paris_battlefield_smoke_light_m"] = loadfx("vfx/map/mp_paris_s2/paris_battlefield_smoke_light_m");
	level.var_611["paris_smoke_pillar_black_xlarge_slow_w"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_pillar_black_xlarge_slow_w");
	level.var_611["paris_fire_lp_m_base_windy_vf"] = loadfx("vfx/map/mp_paris_s2/paris_fire_lp_m_base_windy_vf");
	level.var_611["paris_moths_small"] = loadfx("vfx/map/mp_paris_s2/paris_moths_small");
	level.var_611["paris_smoke_medium_2"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_medium_2");
	level.var_611["paris_smoke_chimney_thin_sm"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_chimney_thin_sm");
	level.var_611["paris_smoke_chimney_sm"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_chimney_sm");
	level.var_611["vf_wind_mp_paris_s2"] = loadfx("vfx/vectorfield/vf_wind_mp_paris_s2");
	level.var_611["paris_smoke_chimney_locked_sm"] = loadfx("vfx/map/mp_paris_s2/paris_smoke_chimney_locked_sm");
	level.var_611["mp_paris_ground_smoke_low_fill_lrg_vert"] = loadfx("vfx/map/mp_paris_s2/mp_paris_ground_smoke_low_fill_lrg_vert");
	level.var_611["mp_paris_fire_column_small_03"] = loadfx("vfx/map/mp_paris_s2/mp_paris_fire_column_small_03");
	level.var_611["mp_paris_fire_column_small_02"] = loadfx("vfx/map/mp_paris_s2/mp_paris_fire_column_small_02");
	level.var_611["mp_paris_fire_column_small_black_02"] = loadfx("vfx/map/mp_paris_s2/mp_paris_fire_column_small_black_02");
	level.var_611["mp_paris_ground_smoke_low_fill_lrg"] = loadfx("vfx/map/mp_paris_s2/mp_paris_ground_smoke_low_fill_lrg");
	level.var_611["mp_paris_smk_medium_1"] = loadfx("vfx/map/mp_paris_s2/mp_paris_smk_medium_1");
	level.var_611["mp_paris_smk_medium_black_1"] = loadfx("vfx/map/mp_paris_s2/mp_paris_smk_medium_black_1");
	level.var_611["mp_paris_fire_barn_01"] = loadfx("vfx/map/mp_paris_s2/mp_paris_fire_barn_01");
	level.var_611["paris_fire_medium_1"] = loadfx("vfx/map/mp_paris_s2/paris_fire_medium_1");
	level.var_611["mp_paris_fire_damage_tree"] = loadfx("vfx/map/mp_paris_s2/mp_paris_fire_damage_tree");
	level.var_611["mp_paris_radiotower_fire_2"] = loadfx("vfx/map/mp_paris_s2/mp_paris_radiotower_fire_2");
	level.var_611["ambient_smoke_white_windy_lp"] = loadfx("vfx/smoke/ambient_smoke_white_windy_lp");
	level.var_611["dday_fire_barn_02"] = loadfx("vfx/map/mp_d_day/dday_fire_barn_02");
	level.var_611["dday_fire_barn_01"] = loadfx("vfx/map/mp_d_day/dday_fire_barn_01");
	level.var_611["dday_ground_smoke_low_fill"] = loadfx("vfx/map/mp_d_day/dday_ground_smoke_low_fill");
	level.var_611["aa_fire_lp_ceiling_beam_small"] = loadfx("vfx/map/mp_aachen/aa_fire_lp_ceiling_beam_small");
	level.var_611["aa_fire_medium_1"] = loadfx("vfx/map/mp_aachen/aa_fire_medium_1");
	level.var_611["aa_smk_large_vista_1"] = loadfx("vfx/map/mp_aachen/aa_smk_large_vista_1");
	level.var_611["aa_fire_ground_small_1"] = loadfx("vfx/map/mp_aachen/aa_fire_ground_small_1");
	level.var_611["aa_ash_and_embers_large"] = loadfx("vfx/map/mp_aachen/aa_ash_and_embers_large");
	level.var_611["aa_fire_lp_ceiling_beam_med"] = loadfx("vfx/map/mp_aachen/aa_fire_lp_ceiling_beam_med");
	level.var_611["aa_smk_embers_fire_small"] = loadfx("vfx/map/mp_aachen/aa_smk_embers_fire_small");
	level.var_611["leaves_fall_gentlewind_tree"] = loadfx("vfx/wind/leaves_fall_gentlewind_tree");
	level.var_611["smoke_chimney_small_dark_sheet_lrg"] = loadfx("vfx/smoke/smoke_chimney_small_dark_sheet_lrg");
	level.var_611["smoke_chimney_small_dark_sheet_sm"] = loadfx("vfx/smoke/smoke_chimney_small_dark_sheet_sm");
	level.var_611["smoke_chimney_small_dark_sheet"] = loadfx("vfx/smoke/smoke_chimney_small_dark_sheet");
	level.var_611["smk_damage_b_lrg_noembers"] = loadfx("vfx/smoke/smk_damage_b_lrg_noembers");
	level.var_611["room_smoke_black_ember_lrg"] = loadfx("vfx/smoke/room_smoke_black_ember_lrg");
	level.var_611["smk_damage_b_sm_noembers"] = loadfx("vfx/smoke/smk_damage_b_sm_noembers");
	level.var_611["dust_falling_lp_sm"] = loadfx("vfx/dust/dust_falling_lp_sm");
	level.var_611["dust_debris_blowing_sm_lp"] = loadfx("vfx/map/mp_sector17/dust_debris_blowing_sm_lp");
	level.var_611["dust_blowing_ground_slow_light_lp"] = loadfx("vfx/dust/dust_blowing_ground_slow_light_lp");
	level.var_611["smoke_chimney_small_dark_4"] = loadfx("vfx/smoke/smoke_chimney_small_dark_4");
	level.var_611["smoke_chimney_small_dark_5"] = loadfx("vfx/smoke/smoke_chimney_small_dark_5");
	level.var_611["falling_water_drip_central_fast_sml"] = loadfx("vfx/water/falling_water_drip_central_fast_sml");
	level.var_611["fire_lp_m_base_windy_vf"] = loadfx("vfx/fire/fire_lp_m_base_windy_vf");
	level.var_611["smk_damage_c_sm_fwind"] = loadfx("vfx/smoke/smk_damage_c_sm_fwind");
	level.var_611["dday_house_interior_ash_embers_falling"] = loadfx("vfx/map/mp_d_day/dday_house_interior_ash_embers_falling");
	level.var_611["smoke_plume_02"] = loadfx("vfx/map/mp_blackbox/smoke_plume_02");
	level.var_611["fire_crawl_wall_lrg_cheap"] = loadfx("vfx/fire/fire_crawl_wall_lrg_cheap");
	level.var_611["ark_steam_stack_black"] = loadfx("vfx/map/mp_zombie_ark/ark_steam_stack_black");
	level.var_611["smoke_pillar_white_large_slow"] = loadfx("vfx/smoke/smoke_pillar_white_large_slow");
	level.var_611["ark_steam_stack"] = loadfx("vfx/map/mp_zombie_ark/ark_steam_stack");
	level.var_611["smk_wall_lrg"] = loadfx("vfx/smoke/smk_wall_lrg");
	level.var_611["smoke_chimney_small_dark_3"] = loadfx("vfx/smoke/smoke_chimney_small_dark_3");
	level.var_611["smoke_chimney_small_dark_2"] = loadfx("vfx/smoke/smoke_chimney_small_dark_2");
	level.var_611["battlefield_ash_falling"] = loadfx("vfx/wind/battlefield_ash_falling");
	level.var_611["insects_flies_landing"] = loadfx("vfx/animal/insects_flies_landing");
	level.var_611["smoke_pillar_black_xlarge_slow_w"] = loadfx("vfx/smoke/smoke_pillar_black_xlarge_slow_w");
	level.var_611["steam_chimney_vertical_small"] = loadfx("vfx/steam/steam_chimney_vertical_small");
	level.var_611["leaves_fall_gentlewind_area"] = loadfx("vfx/wind/leaves_fall_gentlewind_area");
	level.var_611["leaves_small_fall_vector_lightefx"] = loadfx("vfx/wind/leaves_small_fall_vector_lightefx");
	level.var_611["ambient_smoke_black_tall_lp"] = loadfx("vfx/smoke/ambient_smoke_black_tall_lp");
	level.var_611["battlefield_smoke_light_m"] = loadfx("vfx/smoke/battlefield_smoke_light_m");
	level.var_611["smk_damage_b_sm_nofire"] = loadfx("vfx/smoke/smk_damage_b_sm_nofire");
	level.var_611["burning_roof_smoke"] = loadfx("vfx/smoke/burning_roof_smoke");
	level.var_611["smoke_pillar_black_xlarge_slow"] = loadfx("vfx/smoke/smoke_pillar_black_xlarge_slow");
	level.var_611["mp_bigb_vista_smk_stack"] = loadfx("vfx/map/mp_bigben/mp_bigb_vista_smk_stack");
	level.var_611["paper_np_1_windblown_slw_e"] = loadfx("vfx/wind/paper_np_1_windblown_slw_e");
	level.var_611["smoke_stack_tall"] = loadfx("vfx/test/jhall_text_vfx/smoke_stack_tall");
	level.var_611["dust_falling_debris_lp_sm"] = loadfx("vfx/dust/dust_falling_debris_lp_sm");
	level.var_611["smoke_chimney_light_black_v"] = loadfx("vfx/smoke/smoke_chimney_light_black_v");
	level.var_611["smoke_chimney_small"] = loadfx("vfx/smoke/smoke_chimney_small");
	level.var_611["smoke_chimney_extra_small"] = loadfx("vfx/smoke/smoke_chimney_extra_small");
	level.var_611["dust_blowing_ground_slow"] = loadfx("vfx/dust/dlc/dust_blowing_ground_slow");
	level.var_611["paper_scrap_windblown_runner_light"] = loadfx("vfx/wind/paper_scrap_windblown_runner_light");
	level.var_611["dust_falling_debris_a"] = loadfx("vfx/map/mp_kremlin/dust_falling_debris_a");
	level.var_611["test_effect"] = loadfx("vfx/test/test_fx");
	level.var_611["fx_window_godrays_01"] = loadfx("vfx/map/mp_paris_s2/fx_window_godrays_01");
	level.var_611["tra_oil_spill_fire_a"] = loadfx("vfx/map/train/tra_oil_spill_fire_a");
	level.var_611["fire_lrg"] = loadfx("vfx/map/mp_paris_s2/fire_lrg");
}