/*******************************************************************
 * Decompiled By: Bog
 * Decompiled File: crash_anim.gsc
 * Game: Call of Duty: Advanced Warfare
 * Platform: PC
 * Function Count: 6
 * Decompile Time: 114 ms
 * Timestamp: 4/22/2024 2:26:44 AM
*******************************************************************/

//Function Number: 1
main()
{
	if(level.nextgen)
	{
		anim.forced_s1_motionset = 1;
	}

	player_anims();
	npc_anims();
	vehicles_anims();
	prop_anims();
	script_model_anims();
}

//Function Number: 2
player_anims()
{
	level.scr_animtree["rig"] = #animtree;
	level.scr_model["rig"] = "viewbody_sentinel_arctic_mitchell";
	level.scr_anim["rig"]["skyjack_wingland_player"] = %crash_skyjack_wingland_player;
	maps\_anim::addnotetrack_flag("rig","start_player_control","player_fly","skyjack_wingland_player");
	maps\_anim::addnotetrack_flag("rig","player_magon","crash_lighting_screen_dof","skyjack_wingland_player");
	maps\_anim::addnotetrack_flag("rig","end_player_control","stop_player_fly","skyjack_wingland_player");
	level.scr_anim["rig"]["skyjack_wingland_player_L"] = %crash_skyjack_wingland_player_l;
	level.scr_anim["rig"]["skyjack_wingland_player_R"] = %crash_skyjack_wingland_player_r;
	level.scr_anim["rig"]["skyjack_setcharge_player"] = %crash_skyjack_setcharge_player;
	level.scr_anim["rig"]["skyjack_explosion_player"] = %crash_skyjack_explosion_player;
	maps\_anim::addnotetrack_flag("rig","push_off_plane","start_clouds_again","skyjack_explosion_player");
	level.scr_animtree["rig_hands"] = #animtree;
	level.scr_model["rig_hands"] = "viewbody_sentinel_arctic_mitchell";
	level.scr_anim["rig_hands"]["skyjack_mag_glove_enter_player"] = %crash_skyjack_mag_grip_player_enter;
	level.scr_anim["rig_hands"]["skyjack_mag_glove_loop_player"][0] = %crash_skyjack_mag_grip_player_loop;
	level.scr_anim["rig_hands"]["skyjack_mag_glove_exit_player"] = %crash_skyjack_mag_grip_player_exit;
	level.scr_anim["rig"]["crash_atlas_plane_crash_player"] = %crash_atlas_plane_crash_player;
	level.scr_anim["rig"]["prebunker_end_player"] = %crash_prebunker_end_player;
	maps\_anim::addnotetrack_customfunction("rig","rt_hand_on_crate",::maps\crash_crash_site::razorback_rumble,"prebunker_end_player");
	maps\_anim::addnotetrack_customfunction("rig","gun_up",::maps\crash_crash_site::razorback_gun_enable,"prebunker_end_player");
	level.scr_anim["rig"]["icecave_enter"] = %crash_icecave_enter_player;
	level.scr_anim["rig"]["player_bridge_smash"] = %crash_ice_bridge_arm_smash_player;
	level.scr_anim["rig"]["player_bridge_explode"] = %crash_ice_bridge_resonance_explodes_player;
	level.scr_anim["rig"]["player_bridge_throw"] = %crash_ice_bridge_throw_player;
	level.scr_anim["rig"]["narrowcave_water_breach_enter"] = %crash_narrowcave_water_breach_enter_player;
	level.scr_anim["rig"]["narrowcave_water_breach_idle"][0] = %crash_narrowcave_water_breach_idle_player;
	level.scr_anim["rig"]["narrowcave_water_breach_old"] = %crash_narrowcave_water_breach_player;
	level.scr_anim["rig"]["narrowcave_water_breach"] = %crash_narrowcave_water_breach_guide_player;
	level.scr_anim["rig"]["reso_wall"] = %seo_hotel_breach_vm;
	level.scr_animtree["rig_hands1"] = #animtree;
	level.scr_model["rig_hands1"] = "viewbody_sentinel_arctic_mitchell";
	level.scr_anim["rig_hands1"]["control_fall"] = %crash_teleport_fall_player;
	level.scr_anim["rig_hands1"]["fall_grab"] = %crash_ledgegrab_r_hand_start;
	level.scr_anim["rig_hands1"]["fall_loop"][0] = %crash_ledgegrab_r_hand_loop;
	level.scr_anim["rig_hands1"]["fall_recover"] = %crash_ledgegrab_r_hand_recover;
	level.scr_anim["rig_hands"]["lake_fall"] = %crash_lake_fall_player;
	level.scr_animtree["rig2"] = #animtree;
	level.scr_model["rig2"] = "viewbody_sentinel_arctic_mitchell";
	level.scr_anim["rig2"]["gideon_scene"] = %crash_gideon_rescue_player;
	level.scr_anim["rig"]["avalanche_exit"] = %crash_exfil_player;
	maps\_anim::addnotetrack_customfunction("rig","jump_window_start",::maps\crash_exfil::exfil_player_jump,"avalanche_exit");
	maps\_anim::addnotetrack_customfunction("rig","jump_window_end",::maps\crash_exfil::exfil_player_jump_fail,"avalanche_exit");
	maps\_anim::addnotetrack_flag("rig","start_gideon","start_gideon_exfil","avalanche_exit");
	maps\_anim::addnotetrack_flag("rig","start_fail_anims","start_vtol_exfil","avalanche_exit");
	maps\_anim::addnotetrack_flag("rig","fade_out","vtol_takedown_done","avalanche_exit");
	level.scr_anim["rig"]["avalanche_death"] = %crash_avalanche_playerarms_death;
	level.scr_animtree["rig3"] = #animtree;
	level.scr_model["rig3"] = "viewhands_player_sas";
	level.scr_anim["rig3"]["knife_takedown"] = %castle_6_2_spotlight_kill_player;
}

//Function Number: 3
npc_anims()
{
	level.scr_anim["cormack"]["prone_aim_idle"][0] = %prone_aim_idle;
	level.scr_anim["cormack"]["prone_2_stand"] = %prone_2_stand;
	level.scr_anim["cormack"]["skyjack_intro_cormack"] = %crash_skyjack_intro_cormack;
	level.scr_anim["cormack"]["skyjack_loop_cormack"][0] = %crash_skyjack_loop_cormack;
	level.scr_anim["cormack"]["skyjack_explosion_cormack"] = %crash_skyjack_explosion_cormack;
	level.scr_anim["cormack"]["atlas_plane_crash"] = %crash_atlas_plane_crash_cormack;
	maps\_anim::addnotetrack_flag("cormack","sd_crsh_crmk_there1","zero_view","atlas_plane_crash");
	maps\_anim::addnotetrack_customfunction("cormack","jetpack_switch",::maps\crash_crash_site::cormack_jetpack_switch,"atlas_plane_crash");
	maps\_anim::addnotetrack_flag("cormack","jetpack_switch","unhide_cargo","atlas_plane_crash");
	maps\_anim::addnotetrack_customfunction("cormack","helmet_open",::maps\crash_utility::cormack_helmet_open,"atlas_plane_crash");
	maps\_anim::addnotetrack_customfunction("cormack","helmet_close",::maps\crash_utility::cormack_helmet_close,"atlas_plane_crash");
	level.scr_anim["ilana"]["atlas_plane_crash"] = %crash_atlas_plane_crash_ilona;
	level.scr_anim["sent1"]["atlas_plane_crash"] = %crash_atlas_plane_crash_engineer01;
	level.scr_anim["sent2"]["atlas_plane_crash"] = %crash_atlas_plane_crash_engineer02;
	level.scr_anim["sent3"]["atlas_plane_crash"] = %crash_atlas_plane_crash_engineer03;
	level.scr_anim["sent4"]["atlas_plane_crash"] = %crash_atlas_plane_crash_lookout;
	level.scr_anim["sent5"]["atlas_plane_crash"] = %crash_atlas_plane_crash_crateguy1;
	level.scr_anim["sent6"]["atlas_plane_crash"] = %crash_atlas_plane_crash_crateguy2;
	level.scr_anim["sent2"]["stand_exposed_wave_target_spotted"] = %stand_exposed_wave_target_spotted;
	level.scr_anim["sent1"]["atlas_plane_crash_craig"] = %crash_atlas_plane_crash_craig;
	level.scr_anim["sent2"]["atlas_plane_crash_tony"] = %crash_atlas_plane_crash_tony;
	level.scr_anim["cormack"]["prebunker_start_push_fast_cormack"] = %crash_prebunker_start_push_fast_cormack;
	level.scr_anim["cormack"]["prebunker_start_push_slow_cormack"] = %crash_prebunker_start_push_slow_cormack;
	level.scr_anim["cormack"]["prebunker_intro_cormack"] = %crash_prebunker_intro_cormack;
	level.scr_anim["cormack"]["prebunker_loop_cormack"][0] = %crash_prebunker_loop_cormack;
	level.scr_anim["cormack"]["prebunker_end_cormack"] = %crash_prebunker_end_cormack;
	level.scr_anim["goliath"]["prebunker_end_mech"] = %crash_prebunker_end_mech;
	level.scr_anim["guy1"]["guy_enter_mobile_turret"] = %x4walker_wheels_enter_right_npc;
	level.scr_anim["cormack"]["bunker_spot_missiles"] = %crash_bunker_spot_missiles_cormack;
	level.scr_anim["cormack"]["icecave_enter"] = %crash_icecave_enter_cormack;
	level.scr_anim["cormack"]["cave_intro_loop"][0] = %crash_prometheus_drone_loop_cormack;
	level.scr_anim["cormack"]["head_down_tunnel"] = %crash_prometheus_drone_end_cormack;
	maps\_anim::addnotetrack_customfunction("cormack","helmet_open",::maps\crash_utility::cormack_helmet_open,"head_down_tunnel");
	level.scr_anim["ilana"]["bunker_spot_missiles"] = %crash_bunker_spot_missiles_ilona;
	level.scr_anim["ilana"]["icecave_enter"] = %crash_icecave_enter_ilana;
	level.scr_anim["ilana"]["cave_intro_loop"][0] = %crash_prometheus_drone_loop_ilana;
	level.scr_anim["ilana"]["head_down_tunnel"] = %crash_prometheus_drone_end_ilana;
	level.scr_anim["cormack"]["flare_cave_walk"] = %crash_flare_cave_cormack;
	level.scr_anim["ilana"]["flare_cave_walk"] = %crash_flare_cave_ilona;
	level.scr_anim["bunker_guy03"]["icecave_enter"] = %crash_icecave_enter_guy1;
	level.scr_anim["goliath"]["icecave_enter"] = %crash_icecave_enter_goliath;
	maps\_anim::addnotetrack_customfunction("goliath","show",::maps\crash_crash_site::cave_entry_goliath_show,"icecave_enter");
	level.scr_anim["turkey_guy_1"]["turkey_idle"][0] = %stealth_crouch_idle;
	level.scr_anim["turkey_guy_2"]["turkey_idle"][0] = %crouch_cover_stand_aim_down;
	level.scr_anim["turkey_guy_3"]["turkey_idle"][0] = %casual_crouch_idle;
	level.scr_anim["turkey_guy"]["turkey_rappel"] = %berlin_rappel_npc;
	level.scr_anim["teamleader"]["turkey_shoot"] = %crash_turkey_shoot_teamleader;
	level.scr_anim["squadleader"]["turkey_shoot"] = %crash_turkey_shoot_squadleader;
	level.scr_anim["rappeler1"]["turkey_shoot"] = %crash_turkey_shoot_rappeler1;
	level.scr_anim["rappeler2"]["turkey_shoot"] = %crash_turkey_shoot_rappeler2;
	level.scr_anim["comms"]["turkey_shoot"] = %crash_turkey_shoot_comms;
	level.scr_anim["gearguy1"]["turkey_shoot"][0] = %crash_turkey_shoot_gearguy1;
	level.scr_anim["gearguy2"]["turkey_shoot"][0] = %crash_turkey_shoot_gearguy1;
	level.scr_anim["droneguy"]["turkey_shoot"] = %crash_turkey_shoot_droneguy;
	level.scr_anim["rappeler1"]["turkey_shoot_idle"][0] = %crash_turkey_shoot_rappeler1_loop;
	level.scr_anim["rappeler2"]["turkey_shoot_idle"][0] = %crash_turkey_shoot_rappeler2_loop;
	level.scr_anim["droneguy"]["turkey_shoot_idle"][0] = %crash_turkey_shoot_droneguy_loop;
	level.scr_anim["patroller1"]["turkey_shoot_idle"][0] = %ny_manhattan_radio_talk_idle;
	level.scr_anim["patroller2"]["turkey_shoot_idle"][0] = %cliff_guarda_idle;
	level.scr_anim["teamleader"]["turkey_react"] = %cqb_stand_react_a;
	level.scr_anim["squadleader"]["turkey_react"] = %cqb_stand_react_c;
	level.scr_anim["rappeler1"]["turkey_react"] = %seo_react_to_war_idle;
	level.scr_anim["rappeler2"]["turkey_react"] = %seo_react_to_war_idle;
	level.scr_anim["comms"]["turkey_react"] = %cqb_stand_react_c;
	level.scr_anim["gearguy1"]["turkey_react"] = %cqb_stand_react_e;
	level.scr_anim["gearguy2"]["turkey_react"] = %cqb_stand_react_a;
	level.scr_anim["droneguy"]["turkey_react"] = %seo_react_to_war_idle;
	level.scr_anim["cormack"]["turkey_shoot"] = %crash_turkey_shoot_insertion_cormack;
	level.scr_anim["ilana"]["turkey_shoot"] = %crash_turkey_shoot_insertion_ilona;
	level.scr_anim["drop_pod_1"]["drop_pod_idle"][0] = %wounded_carry_closet_idle_wounded;
	level.scr_anim["drop_pod_2"]["drop_pod_idle"][0] = %dc_burning_bunker_sit_idle;
	level.scr_anim["drop_pod_3"]["drop_pod_idle"][0] = %cliff_guarda_idle;
	level.scr_anim["drop_pod_4"]["drop_pod_idle"][0] = %cliff_guardb_idle;
	level.scr_anim["drop_pod_1"]["drop_pod_react"] = %cqb_stand_react_a;
	level.scr_anim["drop_pod_2"]["drop_pod_react"] = %cqb_stand_react_c;
	level.scr_anim["drop_pod_3"]["drop_pod_react"] = %cqb_stand_react_e;
	level.scr_anim["drop_pod_4"]["drop_pod_react"] = %cqb_stand_react_e;
	level.scr_anim["enemy_dying"]["cave_loop"][0] = %seo_soldiers_dying_idle_guy01;
	level.scr_anim["medic_01"]["cave_loop"][0] = %africa_militia_mortar_idle;
	level.scr_anim["medic_02"]["cave_loop"][0] = %africa_price_submerge_idle;
	level.scr_anim["radio_guy"]["cave_loop"][0] = %ny_manhattan_radio_talk_idle;
	level.scr_anim["pod_guy"]["cave_loop"][0] = %afgan_caves_price_rappel_idle;
	level.scr_anim["radio_guy"]["knife_takedown"] = %castle_6_2_spotlight_kill_guard;
	level.scr_anim["back_guy_00"]["cave_loop"][0] = %seo_react_to_war_idle;
	level.scr_anim["back_guy_01"]["cave_loop"][0] = %bet_casual_startstop_idle_gideon;
	level.scr_anim["back_guy_02"]["cave_loop"][0] = %seo_standing_soldier_idle_01;
	level.scr_anim["enemy_stealth_back_patrol_01"]["cave_loop"][0] = %seo_standing_soldier_idle_01;
	level.scr_anim["enemy_stealth_back_patrol_00"]["cave_loop"][0] = %seo_react_to_war_idle;
	level.scr_anim["enemy_stealth_back_patrol_01"]["casual_walk"][0] = %det_casual_walk_slow_cormack;
	level.scr_anim["enemy_stealth_back_patrol_00"]["casual_walk"][0] = %det_casual_walk_slow_cormack;
	level.scr_anim["back_guy_00"]["pod_react"] = %cqb_stand_react_a;
	level.scr_anim["back_guy_01"]["pod_react"] = %cqb_stand_react_c;
	level.scr_anim["back_guy_02"]["pod_react"] = %stand_exposed_dive;
	level.scr_anim["enemy_stealth_back_patrol_01"]["pod_react"] = %cqb_stand_react_a;
	level.scr_anim["enemy_stealth_back_patrol_00"]["pod_react"] = %cqb_stand_react_c;
	level.scr_anim["pod_rappel"]["pod_rappel"] = %berlin_granite_team_rappel_drop;
	level.scr_anim["jumpers"]["big_jump_down"] = %seo_pre_lassist_1st_jump_npc2_e3;
	level.scr_animtree["goliath_rig"] = #animtree;
	level.scr_model["goliath_rig"] = "npc_exo_armor_base";
	level.scr_anim["goliath_rig"]["goliath_bridge_throw"] = %crash_ice_bridge_throw_goliath;
	level.scr_anim["cormack"]["cormack_bridge_approach"] = %crash_ice_bridge_approach_trigger_cormack;
	level.scr_anim["cormack"]["cormack_bridge_wait"][0] = %crash_ice_bridge_wait_idle_cormack;
	level.scr_anim["cormack"]["cormack_bridge_surprise"] = %crash_ice_bridge_surprise_attack_cormack;
	level.scr_anim["cormack"]["cormack_bridge_smash"] = %crash_ice_bridge_throw_cormack;
	maps\_anim::addnotetrack_customfunction("cormack","distort_begin",::maps\crash_utility::cormack_helmet_close,"cormack_bridge_smash");
	level.scr_anim["cormack"]["cormack_bridge_throw2"] = %crash_ice_bridge_throw2_cormack;
	level.scr_anim["cormack"]["cormack_bridge_throw"] = %crash_ice_bridge_throw_success_cormack;
	level.scr_anim["cormack"]["friendly_bridge_explode"] = %crash_ice_bridge_resonance_explodes_cormack;
	maps\_anim::addnotetrack_customfunction("cormack","helmet_open",::maps\crash_utility::cormack_helmet_open,"friendly_bridge_explode");
	level.scr_anim["goliath"]["goliath_bridge_surprise"] = %crash_ice_bridge_surprise_attack_goliath;
	level.scr_anim["goliath"]["goliath_bridge_smash"] = %crash_ice_bridge_arm_smash_goliath;
	level.scr_anim["goliath"]["goliath_bridge_explode"] = %crash_ice_bridge_resonance_explodes_goliath;
	level.scr_anim["goliath"]["goliath_bridge_death"] = %crash_ice_bridge_death_pose_goliath;
	level.scr_anim["goliath"]["goliath_bridge_throw"] = %crash_ice_bridge_throw_goliath;
	level.scr_anim["goliath"]["goliath_bridge_throw2"] = %crash_ice_bridge_throw2_goliath;
	level.scr_anim["ilana"]["ilana_bridge_throw"] = %crash_ice_bridge_throw_ilona;
	level.scr_anim["ilana"]["friendly_bridge_explode"] = %crash_ice_bridge_resonance_explodes_ilana;
	level.scr_animtree["goliathdead"] = #animtree;
	level.scr_model["goliathdead"] = "npc_exo_armor_base";
	level.scr_anim["goliathdead"]["goliath_bridge_death"] = %crash_ice_bridge_death_pose_goliath;
	level.scr_anim["cormack"]["narrowcave_search"] = %crash_narrowcave_search_cormack;
	level.scr_anim["cormack"]["narrowcave_search_traverse_sec1"] = %crash_narrowcave_search_traverse_sec1_cormack;
	level.scr_anim["cormack"]["narrowcave_search_enter"] = %crash_narrowcave_search_enter_wait_cormack;
	level.scr_anim["cormack"]["narrowcave_search_idle"][0] = %crash_narrowcave_search_idle_wait_cormack;
	level.scr_anim["cormack"]["narrowcave_search_exit"] = %crash_narrowcave_search_exit_wait_cormack;
	level.scr_anim["cormack"]["narrowcave_traverse_sec1"] = %crash_narrowcave_traverse_sec1_cormack;
	maps\_anim::addnotetrack_customfunction("cormack","r_crsh_crmk_toheadto",::maps\crash_caves::narrow_cave_cormack_radio,"narrowcave_traverse_sec1");
	maps\_anim::addnotetrack_customfunction("cormack","r_crsh_grdn5_static4",::maps\crash_caves::narrow_cave_radio_response,"narrowcave_traverse_sec1");
	maps\_anim::addnotetrack_flag("cormack","stumble","narrow_cave_rumble","narrowcave_traverse_sec1");
	level.scr_anim["cormack"]["narrowcave_sec1_traverse_sec2"] = %crash_narrowcave_sec1_traverse_sec2_cormack;
	maps\_anim::addnotetrack_customfunction("cormack","r_crsh_iln_thermals",::maps\crash_caves::narrow_cave_ilona_thermals,"narrowcave_sec1_traverse_sec2");
	level.scr_anim["cormack"]["narrowcave_sec2_enter"] = %crash_narrowcave_sec2_enter_wait_cormack;
	level.scr_anim["cormack"]["narrowcave_sec2_idle"][0] = %crash_narrowcave_sec2_idle_wait_cormack;
	level.scr_anim["cormack"]["narrowcave_sec2_exit"] = %crash_narrowcave_sec2_exit_wait_cormack;
	level.scr_anim["cormack"]["narrowcave_sec2_traverse_floodroom"] = %crash_narrowcave_sec2_traverse_floodroom_cormack;
	level.scr_anim["cormack"]["narrowcave_floodroom_idle"][0] = %crash_narrowcave_floodroom_idle_cormack;
	level.scr_anim["cormack"]["narrowcave_floodroom_break_to_breach"] = %crash_narrowcave_floodroom_break_to_breach_cormack;
	maps\_anim::addnotetrack_customfunction("cormack","helmet_close",::maps\crash_utility::cormack_helmet_close,"narrowcave_floodroom_break_to_breach");
	level.scr_anim["cormack"]["narrowcave_pre_breach_idle"][0] = %crash_narrowcave_pre_breach_idle_cormack;
	level.scr_anim["cormack"]["narrowcave_water_breach"] = %crash_narrowcave_water_breach_cormack;
	maps\_anim::addnotetrack_flag("cormack","zero_view","zero_breach_view","narrowcave_water_breach");
	maps\_anim::addnotetrack_flag("cormack","start_player","cormack_breach_ready","narrowcave_water_breach");
	maps\_anim::addnotetrack_flag("cormack","start_enemies","start_breach_enemies","narrowcave_water_breach");
	maps\_anim::addnotetrack_customfunction("cormack","swap_axe",::maps\crash_caves::narrow_cave_swap_axe,"narrowcave_water_breach");
	maps\_anim::addnotetrack_customfunction("cormack","axe_trail",::maps\crash_fx::narrow_cave_axe_throw,"narrowcave_water_breach");
	level.scr_anim["cormack"]["narrowcave_water_breach_fire"] = %crash_narrowcave_water_breach_fire_cormack;
	level.scr_anim["cormack"]["narrowcave_water_breach_mantle"] = %crash_narrowcave_water_breach_mantle_cormack;
	level.scr_anim["ilana"]["narrowcave_search"] = %crash_narrowcave_search_ilona;
	level.scr_anim["ilana"]["narrowcave_search_idle"][0] = %crash_narrowcave_search_idle_wait_ilona;
	level.scr_anim["ilana"]["narrowcave_search_traverse_sec1"] = %crash_narrowcave_search_traverse_sec1_ilona;
	level.scr_anim["ilana"]["narrowcave_sec1_idle"][0] = %crash_narrowcave_sec1_idle_wait_ilona;
	level.scr_anim["ilana"]["narrowcave_sec1_traverse_sec2"] = %crash_narrowcave_sec1_traverse_sec2_ilona;
	level.scr_anim["ilana"]["narrowcave_sec2_idle"][0] = %crash_narrowcave_sec2_idle_wait_ilona;
	level.scr_anim["ilana"]["narrowcave_sec2_traverse_floodroom"] = %crash_narrowcave_sec2_traverse_floodroom_ilona;
	level.scr_anim["ilana"]["narrowcave_break_to_idle_floodroom"] = %crash_narrowcave_break_to_idle_floodroom_ilona;
	level.scr_anim["ilana"]["narrowcave_idle_floodroom"][0] = %crash_narrowcave_idle_floodroom_ilona;
	level.scr_anim["ilana"]["narrowcave_floodroom_to_breach"] = %crash_narrowcave_floodroom_to_breach_ilona;
	level.scr_anim["ilana"]["narrowcave_pre_breach_idle"][0] = %crash_narrowcave_pre_breach_idle_ilona;
	level.scr_anim["ilana"]["narrowcave_water_breach"] = %crash_narrowcave_water_breach_ilona;
	level.scr_anim["ilana"]["narrowcave_water_breach_fire"] = %crash_narrowcave_water_breach_fire_ilona;
	level.scr_anim["ilana"]["narrowcave_water_breach_mantle"] = %crash_narrowcave_water_breach_mantle_ilona;
	level.scr_anim["breach_enemy_1"]["water_breach_idle"][0] = %crash_narrowcave_water_breach_idle_enemy1;
	level.scr_anim["breach_enemy_2"]["water_breach_idle"][0] = %crash_narrowcave_water_breach_idle_enemy2;
	level.scr_anim["breach_enemy_4"]["water_breach_idle"][0] = %crash_narrowcave_water_breach_idle_enemy4;
	level.scr_anim["breach_enemy_5"]["water_breach_idle"][0] = %crash_narrowcave_water_breach_idle_enemy5;
	level.scr_anim["breach_enemy_6"]["water_breach_idle"][0] = %crash_narrowcave_water_breach_idle_enemy6;
	level.scr_anim["breach_enemy_1"]["water_breach_enemy"] = %crash_narrowcave_water_breach_enemy1;
	level.scr_anim["breach_enemy_2"]["water_breach_enemy"] = %crash_narrowcave_water_breach_enemy2;
	level.scr_anim["breach_enemy_3"]["water_breach_enemy"] = %crash_narrowcave_water_breach_enemy3;
	level.scr_anim["breach_enemy_4"]["water_breach_enemy"] = %crash_narrowcave_water_breach_enemy4;
	level.scr_anim["breach_enemy_5"]["water_breach_enemy"] = %crash_narrowcave_water_breach_enemy5;
	level.scr_anim["breach_enemy_6"]["water_breach_enemy"] = %crash_narrowcave_water_breach_enemy6;
	level.scr_anim["enemy_drop"]["drop_512"] = %traverse_drop_512;
	level.scr_anim["generic"]["stealth_walk"][0] = %stealth_walk;
	level.scr_anim["generic"]["casual_walk"][0] = %patrol_bored_patrolwalk;
	level.scr_anim["generic"]["casual_walk_in"] = %patrol_bored_walk_2_bored;
	level.scr_anim["generic"]["casual_walk_out"] = %patrol_bored_2_walk;
	level.scr_anim["generic"]["casual_walk_idle"] = %patrol_bored_idle;
	level.scr_anim["ilana"]["casual_walk"][0] = %det_casual_walk_slow_cormack;
	level.scr_anim["cormack"]["casual_walk"][0] = %det_casual_walk_slow_cormack;
	level.scr_anim["cormack"]["overlook_intro"] = %crash_overlook_cormack;
	level.scr_anim["ilana"]["overlook_intro"] = %crash_overlook_ilona;
	level.scr_anim["generic"]["unarmed_crouch"][0] = %unarmed_covercrouch_hide_look;
	level.scr_anim["ilana"]["gideon_scene"] = %crash_gideon_rescue_ilana;
	level.scr_anim["cormack"]["gideon_scene"] = %crash_gideon_rescue_cormack;
	level.scr_anim["gideon"]["gideon_scene"] = %crash_gideon_rescue_gideon;
	level.scr_anim["lake_enemy_0"]["gideon_scene"] = %crash_gideon_rescue_guy1;
	level.scr_anim["lake_enemy_1"]["gideon_scene"] = %crash_gideon_rescue_guy2;
	level.scr_anim["generic"]["lake_sniped0"] = %exposed_dive_grenade_b;
	level.scr_anim["generic"]["lake_sniped1"] = %exposed_idle_reacta;
	level.scr_anim["generic"]["lake_sniped2"] = %exposed_idle_reactb;
	level.scr_anim["generic"]["lake_sniped3"] = %exposed_dive_grenade_f;
	level.scr_anim["lake_dead_sniper"]["play_dead"] = %det_school_enter_pt2_npc_deadbody_01;
	level.scr_anim["cormack"]["cormack_lake_start"] = %crash_lake_intro_cormack;
	level.scr_anim["lakeguy"]["lake_ambience0"][0] = %crash_vtol_lake_scene_loop_lookout;
	level.scr_anim["lakeguy"]["lake_ambience1"][0] = %crash_vtol_lake_scene_loop_engineer01;
	level.scr_anim["lakeguy"]["lake_ambience2"][0] = %crash_vtol_lake_scene_loop_engineer02;
	level.scr_anim["lakeguy"]["lake_ambience3"][0] = %crash_vtol_lake_scene_loop_engineer03;
	level.scr_anim["enemy1"]["lake_idle"][0] = %crash_vtol_lake_scene_loop_crateguy1;
	level.scr_anim["enemy2"]["lake_idle"][0] = %crash_vtol_lake_scene_loop_crateguy2;
	level.scr_anim["enemy1"]["lake_hookup"] = %crash_lake_crate_hookup_guy1;
	level.scr_anim["enemy2"]["lake_hookup"] = %crash_lake_crate_hookup_guy2;
	level.scr_anim["lakeguy"]["lake_sniped0"] = %crash_vtol_lake_scene_lookout;
	level.scr_anim["lakeguy"]["lake_sniped1"] = %crash_vtol_lake_scene_engineer01;
	level.scr_anim["lakeguy"]["lake_sniped2"] = %crash_vtol_lake_scene_engineer02;
	level.scr_anim["lakeguy"]["lake_sniped3"] = %crash_vtol_lake_scene_engineer03;
	level.scr_anim["enemy1"]["lake_idle_run"] = %crash_vtol_lake_scene_crateguy1;
	level.scr_anim["enemy2"]["lake_idle_run"] = %crash_vtol_lake_scene_crateguy2;
	level.scr_anim["enemy1"]["lake_loadup"] = %crash_lake_intro_enemy1;
	level.scr_anim["enemy2"]["lake_loadup"] = %crash_lake_intro_enemy2;
	level.scr_anim["generic"]["npc_deadbody_01"][0] = %det_school_enter_pt2_npc_deadbody_01;
	level.scr_anim["generic"]["npc_deadbody_11"][0] = %det_school_enter_pt2_npc_deadbody_11;
	level.scr_anim["generic"]["npc_deadbody_12"][0] = %det_school_enter_pt2_npc_deadbody_12;
	level.scr_anim["gideon"]["vtol_ambush_intro"] = %crash_vtol_ambush_intro_gideon;
	level.scr_anim["gideon"]["vtol_ambush_stinger_loop"][0] = %crash_vtol_ambush_stinger_loop_gideon;
	level.scr_anim["gideon"]["vtol_ambush_vtol_talk"] = %crash_vtol_ambush_vtol_talk_gideon;
	level.scr_anim["gideon"]["vtol_ambush_wave_gideon"] = %crash_vtol_ambush_vtol_wave_gideon;
	maps\_anim::addnotetrack_flag("gideon","crsh_acp_heatsignatures","vo_heat_line","vtol_ambush_wave_gideon");
	maps\_anim::addnotetrack_flag("gideon","crsh_gid_bringitdown2","vo_bringitdown_line","vtol_ambush_wave_gideon");
	level.scr_anim["gideon"]["vtol_ambush_exit_cover"] = %crash_vtol_ambush_exit_cover_gideon;
	level.scr_anim["gideon"]["vtol_sliding_off_cliff_gideon"] = %crash_vtol_sliding_off_cliff_gideon;
	level.scr_anim["gideon"]["vtol_falls_off_cliff_failure_gideon"] = %crash_vtol_falls_off_cliff_failure_gideon;
	level.scr_face["gideon"]["ambush_gid_dealtwith"] = %crash_vtol_ambush_gid_dealtwith;
	level.scr_anim["cormack"]["vtol_ambush_intro"] = %crash_vtol_ambush_intro_cormack;
	level.scr_anim["cormack"]["vtol_ambush_cover_loop"][0] = %crash_vtol_ambush_cover_loop_cormack;
	level.scr_anim["cormack"]["vtol_ambush_fire_stinger"] = %crash_vtol_ambush_fire_stinger_cormack;
	level.scr_anim["cormack"]["vtol_ambush_call_evac_loop"][0] = %crash_vtol_ambush_call_evac_loop_cormack;
	level.scr_anim["ilana"]["vtol_ambush_intro"] = %crash_vtol_ambush_intro_ilona;
	level.scr_anim["ilana"]["vtol_ambush_cover_loop"][0] = %crash_vtol_ambush_cover_loop_ilona;
	level.scr_anim["ilana"]["vtol_ambush_exit_cover"] = %crash_vtol_ambush_exit_cover_ilona;
	level.scr_anim["ilana"]["vtol_ambush_call_evac_loop"][0] = %crash_vtol_ambush_call_evac_loop_ilona;
	level.scr_anim["gideon"]["avalanche_exit"] = %crash_exfil_gideon;
	maps\_anim::addnotetrack_flag("gideon","boost_jump","gideon_boost_jump","avalanche_exit");
	level.scr_anim["cormack"]["avalanche_exit"] = %crash_exfil_cormack;
	maps\_anim::addnotetrack_flag("cormack","cormack_line1","vo_cormack_exfil1","avalanche_exit");
	maps\_anim::addnotetrack_flag("cormack","kingpin_line1","vo_kingpin_exfil","avalanche_exit");
	maps\_anim::addnotetrack_flag("cormack","cormack_line2","vo_cormack_exfil2","avalanche_exit");
	level.scr_anim["ilana"]["avalanche_exit"] = %crash_exfil_ilona;
}

//Function Number: 4
vehicles_anims()
{
	level.scr_animtree["cargo_plane"] = #animtree;
	level.scr_anim["cargo_plane"]["skyjack_loop_plane"][0] = %crash_skyjack_loop_plane;
	level.scr_anim["cargo_plane"]["skyjack_explosion_plane"] = %crash_skyjack_explosion_plane;
	level.scr_anim["cargo_plane"]["atlas_plane_crash_plane"] = %crash_atlas_plane_crash_plane;
	level.scr_animtree["drone_pod"] = #animtree;
	level.scr_model["drone_pod"] = "vehicle_skyjack_drone_pod_ai";
	level.scr_anim["drone_pod"]["skyjack_intro_drone"] = %crash_skyjack_intro_drone;
	level.scr_anim["drone_pod"]["skyjack_loop_drone"][0] = %crash_skyjack_loop_drone;
	level.scr_anim["drone_pod"]["skyjack_explosion_drone"] = %crash_skyjack_explosion_drone;
	level.scr_anim["drone_pod"]["atlas_plane_crash_drone"] = %crash_atlas_plane_crash_drone;
	level.scr_animtree["drone_chute1"] = #animtree;
	level.scr_model["drone_chute1"] = "vehicle_skyjack_drone_pod_parachute_large";
	level.scr_anim["drone_chute1"]["skyjack_explosion_drone"] = %crash_skyjack_explosion_chute1;
	level.scr_anim["drone_chute1"]["atlas_plane_crash"] = %crash_atlas_plane_crash_chute1;
	level.scr_animtree["drone_chute2"] = #animtree;
	level.scr_model["drone_chute2"] = "vehicle_skyjack_drone_pod_parachute_large";
	level.scr_anim["drone_chute2"]["skyjack_explosion_drone"] = %crash_skyjack_explosion_chute2;
	level.scr_anim["drone_chute2"]["atlas_plane_crash"] = %crash_atlas_plane_crash_chute2;
	level.scr_animtree["drone_chute3"] = #animtree;
	level.scr_model["drone_chute3"] = "vehicle_skyjack_drone_pod_parachute_large";
	level.scr_anim["drone_chute3"]["skyjack_explosion_drone"] = %crash_skyjack_explosion_chute3;
	level.scr_anim["drone_chute3"]["atlas_plane_crash"] = %crash_atlas_plane_crash_chute3;
	level.scr_animtree["vtol"] = #animtree;
	level.scr_anim["vtol"]["atlas_plane_crash"] = %crash_atlas_plane_crash_atlas_vtol;
	level.scr_animtree["razorback"] = #animtree;
	level.scr_anim["razorback"]["prebunker_intro_razorback"] = %crash_prebunker_intro_razorback;
	level.scr_anim["razorback"]["prebunker_loop_razorback"][0] = %crash_prebunker_loop_razorback;
	level.scr_anim["razorback"]["prebunker_end_razorback"] = %crash_prebunker_end_razorback;
	maps\_anim::addnotetrack_customfunction("razorback","spawn_mech_and_missiles",::maps\crash_crash_site::razorback_mech,"prebunker_end_razorback");
	level.scr_anim["warbird_deploy"]["mobile_turret_deploy"] = %mobile_turret_deploy_warbird;
	level.scr_anim["mobile_turret"]["guy_enter_mobile_turret"] = %x4walker_wheels_enter_right;
	level.scr_anim["walker_tank"]["fusion_walker_tank_enter"] = %fusion_walker_tank_enter;
	level.scr_anim["walker_tank"]["fusion_walker_tank_fwd_2_left"] = %fusion_walker_tank_fwd_2_left;
	level.scr_anim["walker_tank"]["fusion_walker_tank_fwd_2_right"] = %fusion_walker_tank_fwd_2_right;
	level.scr_anim["walker_tank"]["fusion_walker_tank_fwd_idle"][0] = %fusion_walker_tank_fwd_idle;
	level.scr_anim["walker_tank"]["fusion_walker_tank_left_2_fwd"] = %fusion_walker_tank_left_2_fwd;
	level.scr_anim["walker_tank"]["fusion_walker_tank_left_idle"][0] = %fusion_walker_tank_left_idle;
	level.scr_anim["walker_tank"]["fusion_walker_tank_right_2_fwd"] = %fusion_walker_tank_right_2_fwd;
	level.scr_anim["walker_tank"]["fusion_walker_tank_right_idle"][0] = %fusion_walker_tank_right_idle;
	level.scr_anim["walker_tank"]["fusion_walker_tank_fwd_idle_death"] = %fusion_walker_tank_fwd_idle_death;
	level.scr_anim["walker_tank"]["fusion_walker_tank_left_idle_death"] = %fusion_walker_tank_left_idle_death;
	level.scr_anim["walker_tank"]["fusion_walker_tank_right_idle_death"] = %fusion_walker_tank_right_idle_death;
	maps\_anim::addnotetrack_customfunction("walker_tank","footstep_left_large",::maps\crash_fx::walker_tank_footstep_left);
	maps\_anim::addnotetrack_customfunction("walker_tank","footstep_right_large",::maps\crash_fx::walker_tank_footstep_right);
	maps\_anim::addnotetrack_customfunction("walker_tank","footstep_left_rear_large",::maps\crash_fx::walker_tank_footstep_left_rear);
	maps\_anim::addnotetrack_customfunction("walker_tank","footstep_right_rear_large",::maps\crash_fx::walker_tank_footstep_right_rear);
	level.scr_animtree["drone"] = #animtree;
	level.scr_anim["drone"]["drone_intro"] = %crash_prometheus_drone_drone;
	level.scr_anim["drone"]["drone_lineup"] = %crash_prometheus_drone_release_drone;
	level.scr_anim["drone"]["drone_section_1"] = %crash_prometheus_drone_section1_drone;
	level.scr_anim["drone"]["drone_section_1_loop"][0] = %crash_prometheus_drone_loop1_drone;
	level.scr_anim["drone"]["drone_section_2"] = %crash_prometheus_drone_section2_drone;
	level.scr_anim["drone"]["drone_section_2_loop"][0] = %crash_prometheus_drone_loop2_drone;
	level.scr_anim["drone"]["drone_section_3"] = %crash_prometheus_drone_section3_drone;
	level.scr_anim["drone"]["drone_section_3_loop"][0] = %crash_prometheus_drone_loop3_drone;
	level.scr_anim["drone"]["drone_section_4"] = %crash_prometheus_drone_section4_drone;
	level.scr_anim["drone"]["drone_section_4_loop"][0] = %crash_prometheus_drone_loop4_drone;
	level.scr_anim["drone"]["drone_release_loop"][0] = %crash_prometheus_drone_release_loop_drone;
	level.scr_animtree["vehicle_mil_humvee"] = #animtree;
	level.scr_anim["vehicle_mil_humvee"]["lake_loadup"] = %crash_lake_intro_truck;
	level.scr_animtree["vtol"] = #animtree;
	level.scr_model["vtol"] = "vehicle_xh9_warbird";
	level.scr_anim["vtol"]["lake_hookup"] = %crash_lake_crate_hookup_vtol;
	level.scr_anim["vtol"]["lake_loop"][0] = %crash_lake_intro_loop_vtol;
	level.scr_anim["vtol"]["lake_turn"] = %crash_lake_turn_vtol;
	level.scr_anim["vtol"]["lake_hookup_loop"][0] = %crash_lake_hooked_loop_vtol;
	level.scr_anim["vtol"]["lake_takeoff"] = %crash_lake_takeoff_vtol;
	level.scr_animtree["crashed_vtol"] = #animtree;
	level.scr_anim["crashed_vtol"]["vtol_ambush_fly_intro"] = %crash_vtol_ambush_fly_intro_vtol;
	maps\_anim::addnotetrack_flag("crashed_vtol","gideon_wave","start_gideon_wave_anim","vtol_ambush_fly_intro");
	maps\_anim::addnotetrack_flag("crashed_vtol","start_lockon","vtol_can_lock_on","vtol_ambush_fly_intro");
	maps\_anim::addnotetrack_flag("crashed_vtol","start_lockon","obj_start_exfil","vtol_ambush_fly_intro");
	maps\_anim::addnotetrack_flag("crashed_vtol","hit_early","vtol_hit_early","vtol_ambush_fly_intro");
	maps\_anim::addnotetrack_flag("crashed_vtol","hit_mid","vtol_hit_mid","vtol_ambush_fly_intro");
	maps\_anim::addnotetrack_flag("crashed_vtol","cormack_fires_stinger","cormack_fires_stinger_failsafe","vtol_ambush_fly_intro");
	maps\_anim::addnotetrack_flag("crashed_vtol","missiles_hit","missiles_hit_vtol","vtol_ambush_fly_intro");
	level.scr_anim["crashed_vtol"]["vtol_ambush_stinger_hit_late"] = %crash_vtol_ambush_stinger_hit_late_vtol;
	level.scr_anim["crashed_vtol"]["vtol_ambush_stinger_hit_mid"] = %crash_vtol_ambush_stinger_hit_mid_vtol;
	level.scr_anim["crashed_vtol"]["vtol_ambush_stinger_hit_early"] = %crash_vtol_ambush_stinger_hit_early_vtol;
	level.scr_anim["crashed_vtol"]["ambush_hit_add"] = %crash_vtol_ambush_hit_add_vtol;
	level.scr_anim["crashed_vtol"]["vtol_ambush_crash"] = %crash_vtol_ambush_crash_vtol;
	maps\_anim::addnotetrack_flag("crashed_vtol","start_gideons_animation","start_gideons_animation","vtol_ambush_crash");
	level.scr_anim["crashed_vtol"]["vtol_sliding_off_cliff"] = %crash_vtol_sliding_off_cliff_vtol;
	level.scr_anim["crashed_vtol"]["vtol_falls_off_cliff"] = %crash_vtol_falls_off_cliff_vtol;
	level.scr_anim["crashed_vtol"]["avalanche_exit_fail"] = %crash_exfil_fail_vtol;
	level.scr_animtree["exfil_heli"] = #animtree;
	level.scr_anim["exfil_heli"]["avalanche_exit"] = %crash_exfil_helo;
}

//Function Number: 5
prop_anims()
{
	level.scr_animtree["explosive"] = #animtree;
	level.scr_model["explosive"] = "laser_explosive_crate";
	level.scr_anim["explosive"]["skyjack_setcharge_explosive"] = %crash_skyjack_setcharge_explosive;
	level.scr_animtree["plane_debris"] = #animtree;
	level.scr_model["plane_debris"] = "generic_prop_raven_x3";
	level.scr_anim["plane_debris"]["skyjack_explosion_debris"] = %crash_skyjack_explosion_debris;
	level.scr_animtree["drone_cable"] = #animtree;
	level.scr_model["drone_cable"] = "csh_skyjack_drone_cables";
	level.scr_anim["drone_cable"]["skyjack_explosion_drone"] = %crash_skyjack_explosion_drone_cable;
	level.scr_anim["drone_cable"]["atlas_plane_crash"] = %crash_atlas_plane_crash_cables;
	level.scr_animtree["mini_chutes"] = #animtree;
	level.scr_model["mini_chutes"] = "vehicle_skyjack_drone_pod_parachutes_mini";
	level.scr_anim["mini_chutes"]["skyjack_explosion_drone"] = %crash_skyjack_explosion_mini_chutes;
	maps\_anim::addnotetrack_customfunction("mini_chutes","hide_mini_chutes",::maps\crash_skyjack::mini_chute_hide,"skyjack_explosion_drone");
	level.scr_animtree["razor_cargo"] = #animtree;
	level.scr_model["razor_cargo"] = "atlas_stabilize_crate";
	level.scr_anim["razor_cargo"]["prebunker_intro_crate"] = %crash_prebunker_intro_crate;
	level.scr_anim["razor_cargo"]["prebunker_loop_crate"][0] = %crash_prebunker_loop_crate;
	level.scr_anim["razor_cargo"]["prebunker_end_crate"] = %crash_prebunker_end_crate;
	level.scr_animtree["cs_gun"] = #animtree;
	level.scr_model["cs_gun"] = "generic_prop_raven";
	level.scr_anim["cs_gun"]["plane_crash_player_gun"] = %crash_atlas_plane_crash_player_gun;
	level.scr_animtree["razor_missiles"] = #animtree;
	level.scr_model["razor_missiles"] = "genericprop_x5";
	level.scr_anim["razor_missiles"]["prebunker_end_missiles"] = %crash_prebunker_end_missiles;
	level.scr_animtree["ground_chute"] = #animtree;
	level.scr_model["ground_chute"] = "csh_drone_parachute_01";
	level.scr_anim["ground_chute"]["crash_chute_idle"][0] = %crash_atlas_plane_crash_chute_idle;
	level.scr_animtree["ice_floor"] = #animtree;
	level.scr_model["ice_floor"] = "csh_entry_shelf_ice_floor_01_anim";
	level.scr_anim["ice_floor"]["icecave_enter"] = %crash_icecave_enter_icefloor;
	level.scr_animtree["pro_wall"] = #animtree;
	level.scr_anim["pro_wall"]["head_down_tunnel"] = %crash_prometheus_drone_end_wall;
	level.scr_animtree["turkey_drone"] = #animtree;
	level.scr_anim["turkey_drone"]["turkey_shoot"] = %crash_turkey_shoot_drone;
	level.scr_anim["turkey_drone"]["turkey_shoot_loop"][0] = %crash_turkey_shoot_drone_loop;
	level.scr_anim["turkey_drone"]["turkey_shoot_dead"] = %crash_turkey_shoot_drone_dead;
	level.scr_animtree["goliath_ice_bridge"] = #animtree;
	level.scr_anim["goliath_ice_bridge"]["bridge_throw"] = %crash_ice_bridge_throw_bridge;
	level.scr_anim["goliath_ice_bridge"]["bridge_collapse"] = %crash_ice_bridge_resonance_explodes_bridge;
	level.scr_animtree["ice_bridge_reso"] = #animtree;
	level.scr_model["ice_bridge_reso"] = "npc_resonance_device_base";
	level.scr_anim["ice_bridge_reso"]["reso_device_fall"] = %crash_ice_bridge_throw_reso_device;
	level.scr_anim["ice_bridge_reso"]["reso_device_explode"] = %crash_ice_bridge_resonance_explodes_reso_device;
	level.scr_animtree["ice_bridge_gun"] = #animtree;
	level.scr_model["ice_bridge_gun"] = "npc_hbra3_nocamo";
	level.scr_anim["ice_bridge_gun"]["gun_fall"] = %crash_ice_bridge_throw_player_gun;
	level.scr_animtree["ice_bridge_rock"] = #animtree;
	level.scr_model["ice_bridge_rock"] = "generic_prop_raven_x3";
	level.scr_anim["ice_bridge_rock"]["rock_collapse"][0] = %crash_ice_bridge_ice_chunk_loop;
	level.scr_animtree["water_level"] = #animtree;
	level.scr_model["water_level"] = "generic_prop_raven";
	level.scr_anim["water_level"]["water_level_rising"] = %crash_narrowcave_water_level_rising;
	level.scr_animtree["ice_axe"] = #animtree;
	level.scr_model["ice_axe"] = "generic_prop_raven";
	level.scr_anim["ice_axe"]["narrowcave_floodroom_break_to_breach"] = %crash_narrowcave_floodroom_break_to_breach_axe;
	level.scr_anim["ice_axe"]["narrowcave_pre_breach_idle"][0] = %crash_narrowcave_pre_breach_idle_axe;
	level.scr_animtree["ice_axe_scripted"] = #animtree;
	level.scr_model["ice_axe_scripted"] = "scripted_ice_picker_arctic";
	level.scr_anim["ice_axe_scripted"]["narrowcave_water_breach"] = %crash_narrowcave_water_breach_axe;
	level.scr_animtree["cargo"] = #animtree;
	level.scr_model["cargo"] = "generic_prop_raven";
	level.scr_anim["cargo"]["lake_loadup"] = %crash_lake_intro_cargo;
	level.scr_animtree["crate"] = #animtree;
	level.scr_model["crate"] = "atlas_stabilize_crate";
	level.scr_anim["crate"]["lake_loop"][0] = %crash_lake_intro_loop_crate;
	level.scr_anim["crate"]["lake_shut"] = %crash_vtol_lake_crate;
	level.scr_anim["crate"]["lake_hookup_loop"][0] = %crash_vtol_lake_loop_crate;
	level.scr_anim["crate"]["lake_takeoff"] = %crash_lake_takeoff_crate;
	level.scr_animtree["pulley"] = #animtree;
	level.scr_model["pulley"] = "vehicle_xh9_warbird_pulley";
	level.scr_anim["pulley"]["lake_hookup"] = %crash_lake_crate_hookup_cables;
	level.scr_anim["pulley"]["lake_loop"][0] = %crash_lake_intro_loop_cables;
	level.scr_anim["pulley"]["lake_turn"] = %crash_lake_turn_cables;
	level.scr_anim["pulley"]["lake_hookup_loop"][0] = %crash_lake_hooked_loop_cables;
	level.scr_anim["pulley"]["lake_takeoff"] = %crash_lake_takeoff_cables;
	level.scr_animtree["vtol_cargo"] = #animtree;
	level.scr_model["vtol_cargo"] = "atlas_stabilize_crate";
	level.scr_anim["vtol_cargo"]["vtol_ambush_fly_intro"] = %crash_vtol_ambush_fly_intro_crate;
	level.scr_anim["vtol_cargo"]["vtol_ambush_stinger_hit_late"] = %crash_vtol_ambush_stinger_hit_late_crate;
	level.scr_anim["vtol_cargo"]["vtol_ambush_stinger_hit_mid"] = %crash_vtol_ambush_stinger_hit_mid_crate;
	level.scr_anim["vtol_cargo"]["vtol_ambush_stinger_hit_early"] = %crash_vtol_ambush_stinger_hit_early_crate;
	level.scr_anim["vtol_cargo"]["vtol_ambush_crash"] = %crash_vtol_ambush_crash_crate;
	level.scr_anim["vtol_cargo"]["vtol_sliding_off_cliff"] = %crash_vtol_sliding_off_cliff_crate;
	level.scr_anim["vtol_cargo"]["avalanche_exit"] = %crash_exfil_crate;
	level.scr_anim["vtol_cargo"]["vtol_falls_off_cliff"] = %crash_vtol_falls_off_cliff_crate;
	level.scr_anim["vtol_cargo"]["avalanche_exit_fail"] = %crash_exfil_fail_crate;
	level.scr_anim["vtol_cargo"]["ambush_hit_add"] = %crash_vtol_ambush_hit_add_crate;
	level.scr_animtree["vtol_cables"] = #animtree;
	level.scr_model["vtol_cables"] = "vehicle_xh9_warbird_pulley";
	level.scr_anim["vtol_cables"]["vtol_ambush_fly_intro"] = %crash_vtol_ambush_fly_intro_cables;
	level.scr_anim["vtol_cables"]["vtol_ambush_stinger_hit_late"] = %crash_vtol_ambush_stinger_hit_late_cables;
	level.scr_anim["vtol_cables"]["vtol_ambush_stinger_hit_mid"] = %crash_vtol_ambush_stinger_hit_mid_cables;
	level.scr_anim["vtol_cables"]["vtol_ambush_stinger_hit_early"] = %crash_vtol_ambush_stinger_hit_early_cables;
	level.scr_anim["vtol_cables"]["vtol_ambush_crash"] = %crash_vtol_ambush_crash_cables;
	level.scr_anim["vtol_cables"]["vtol_sliding_off_cliff"] = %crash_vtol_sliding_off_cliff_cables;
	level.scr_anim["vtol_cables"]["vtol_falls_off_cliff"] = %crash_vtol_falls_off_cliff_cables;
	level.scr_anim["vtol_cables"]["avalanche_exit_fail"] = %crash_exfil_fail_cables;
	level.scr_anim["vtol_cables"]["ambush_hit_add"] = %crash_vtol_ambush_hit_add_cables;
	level.scr_animtree["vtol_stinger"] = #animtree;
	level.scr_model["vtol_stinger"] = "genericprop_x5";
	level.scr_anim["vtol_stinger"]["vtol_ambush_fire_stinger_missiles"] = %crash_vtol_ambush_fire_stinger_missiles;
	level.scr_animtree["vtol_launcher"] = #animtree;
	level.scr_model["vtol_launcher"] = "genericprop_x5";
	level.scr_anim["vtol_launcher"]["vtol_ambush_intro"] = %crash_vtol_ambush_intro_stinger;
	level.scr_anim["vtol_launcher"]["vtol_ambush_cover_loop"][0] = %crash_vtol_ambush_cover_loop_stinger;
	level.scr_anim["vtol_launcher"]["vtol_ambush_fire_stinger"] = %crash_vtol_ambush_fire_stinger_stinger;
}

//Function Number: 6
script_model_anims()
{
	level.scr_animtree["pulley_deploy"] = #animtree;
	level.scr_model["pulley_deploy"] = "vehicle_xh9_warbird_pulley";
	level.scr_anim["pulley_deploy"]["mobile_turret_deploy"] = %mobile_turret_deploy_pulley;
	level.scr_animtree["walker_deploy"] = #animtree;
	level.scr_model["walker_deploy"] = "vehicle_x4walker_wheels";
	level.scr_anim["walker_deploy"]["mobile_turret_deploy"] = %mobile_turret_deploy_mobileturret;
}